name: Deploy Principia Paradoxica Site to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/principia-paradoxica-site/**'
      - '.github/workflows/deploy-principia-paradoxica-site.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/principia-paradoxica-site

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy static files to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./