/**
 * @fileoverview Complete 8x8 Trigram Relationship Matrix
 * Defines all possible relationships between trigrams based on Wu Xing,
 * Yin-Yang opposition, and mythopoetic principles
 */

import { TRIGRAMS, RELATION_TYPES } from './trigram-relations.js';

/**
 * @typedef {Object} MatrixEntry
 * @property {string} type - Relationship type from RELATION_TYPES
 * @property {string} context - Context or explanation
 * @property {boolean} [asymmetric] - Whether the relationship is asymmetric
 * @property {string} [symbolic] - Symbolic meaning or metaphor
 * @property {string} [quantum] - Quantum-mythopoetic interpretation
 */

/**
 * Complete 8x8 matrix of trigram relationships
 * @type {Object.<string, Object.<string, MatrixEntry>>}
 */
export const TRIGRAM_MATRIX = {
    // Heaven (QIAN) - Pure Yang, Creative Force
    QIAN: {
        QIAN: { 
            type: RELATION_TYPES.RESONANCE, 
            context: 'pure yang resonance',
            symbolic: 'The Creative meets itself - infinite potential',
            quantum: 'Wave function of pure potentiality'
        },
        DUI:  { 
            type: RELATION_TYPES.GENERATION, 
            context: 'metal generation',
            symbolic: 'Heaven gives birth to the Lake - joy emerging from potential',
            quantum: 'Potential crystallizing into form'
        },
        LI:   { 
            type: RELATION_TYPES.OPPOSITION, 
            context: 'fire opposition',
            symbolic: 'Heaven and Fire - light against light',
            quantum: 'Polarized potential states'
        },
        ZHEN: { 
            type: RELATION_TYPES.SUPPORT, 
            context: 'thunder support',
            symbolic: 'Heaven supports Thunder - power manifesting',
            quantum: 'Potential manifesting as movement'
        },
        XUN:  { 
            type: RELATION_TYPES.TRANSFORMATION, 
            context: 'wind transformation',
            symbolic: 'Heaven transforms into Wind - spirit penetrating form',
            quantum: 'Wave function collapsing into flow'
        },
        KAN:  { 
            type: RELATION_TYPES.CONQUEST, 
            context: 'water conquest',
            symbolic: 'Heaven is conquered by Water - spirit descending into matter',
            quantum: 'Potential dissolving into formlessness'
        },
        GEN:  { 
            type: RELATION_TYPES.RESONANCE, 
            context: 'mountain resonance',
            symbolic: 'Heaven and Mountain - pure form meeting form',
            quantum: 'Potential crystallizing into structure'
        },
        KUN:  { 
            type: RELATION_TYPES.OPPOSITION, 
            context: 'pure yin opposition',
            symbolic: 'Heaven and Earth - pure yang meets pure yin',
            quantum: 'Maximum potential difference'
        }
    },

    // Lake (DUI) - Joy, Reflection
    DUI: {
        QIAN: { 
            type: RELATION_TYPES.GENERATION, 
            context: 'metal generation',
            symbolic: 'Lake is generated by Heaven - joy emerging from potential',
            quantum: 'Form emerging from potential',
            asymmetric: true // Heaven generates Lake, but Lake reflects Heaven
        },
        DUI:  { 
            type: RELATION_TYPES.RESONANCE, 
            context: 'lake resonance',
            symbolic: 'Lake meets Lake - joy reflecting joy',
            quantum: 'Resonant wave patterns'
        },
        LI:   { 
            type: RELATION_TYPES.CONQUEST, 
            context: 'fire conquest',
            symbolic: 'Lake is conquered by Fire - joy transformed by clarity',
            quantum: 'Form dissolving into light'
        },
        ZHEN: { 
            type: RELATION_TYPES.TRANSFORMATION, 
            context: 'thunder transformation',
            symbolic: 'Lake transforms into Thunder - joy becoming movement',
            quantum: 'Form becoming dynamic'
        },
        XUN:  { 
            type: RELATION_TYPES.SUPPORT, 
            context: 'wind support',
            symbolic: 'Lake supports Wind - joy enabling penetration',
            quantum: 'Form enabling flow'
        },
        KAN:  { 
            type: RELATION_TYPES.OPPOSITION, 
            context: 'water opposition',
            symbolic: 'Lake opposes Water - joy meets danger',
            quantum: 'Form meets formlessness'
        },
        GEN:  { 
            type: RELATION_TYPES.RESONANCE, 
            context: 'mountain resonance',
            symbolic: 'Lake and Mountain - joy meeting stillness',
            quantum: 'Form meeting structure'
        },
        KUN:  { 
            type: RELATION_TYPES.GENERATION, 
            context: 'earth generation',
            symbolic: 'Lake generates Earth - joy creating form',
            quantum: 'Form crystallizing into matter'
        }
    },

    // Fire (LI) - Clarity, Illumination
    LI: {
        QIAN: { 
            type: RELATION_TYPES.OPPOSITION, 
            context: 'metal opposition',
            symbolic: 'Fire opposes Heaven - light against potential',
            quantum: 'Light meeting potential'
        },
        DUI:  { 
            type: RELATION_TYPES.CONQUEST, 
            context: 'fire conquest',
            symbolic: 'Fire conquers Lake - clarity dissolving joy',
            quantum: 'Light dissolving form',
            asymmetric: true // Fire conquers Lake, but Lake reflects Fire
        },
        LI:   { 
            type: RELATION_TYPES.RESONANCE, 
            context: 'fire resonance',
            symbolic: 'Fire meets Fire - light amplifying light',
            quantum: 'Resonant light patterns'
        },
        ZHEN: { 
            type: RELATION_TYPES.TRANSFORMATION, 
            context: 'thunder transformation',
            symbolic: 'Fire transforms into Thunder - light becoming movement',
            quantum: 'Light becoming dynamic'
        },
        XUN:  { 
            type: RELATION_TYPES.SUPPORT, 
            context: 'wind support',
            symbolic: 'Fire supports Wind - light enabling penetration',
            quantum: 'Light enabling flow'
        },
        KAN:  { 
            type: RELATION_TYPES.OPPOSITION, 
            context: 'water opposition',
            symbolic: 'Fire opposes Water - light meets darkness',
            quantum: 'Light meets formlessness'
        },
        GEN:  { 
            type: RELATION_TYPES.RESONANCE, 
            context: 'mountain resonance',
            symbolic: 'Fire and Mountain - light meeting stillness',
            quantum: 'Light meeting structure'
        },
        KUN:  { 
            type: RELATION_TYPES.GENERATION, 
            context: 'earth generation',
            symbolic: 'Fire generates Earth - light creating form',
            quantum: 'Light crystallizing into matter'
        }
    },

    // Thunder (ZHEN) - Movement, Arousal
    ZHEN: {
        QIAN: { 
            type: RELATION_TYPES.SUPPORT, 
            context: 'thunder support',
            symbolic: 'Thunder supports Heaven - movement enabling potential',
            quantum: 'Movement enabling potential'
        },
        DUI:  { 
            type: RELATION_TYPES.TRANSFORMATION, 
            context: 'thunder transformation',
            symbolic: 'Thunder transforms Lake - movement becoming joy',
            quantum: 'Movement becoming form'
        },
        LI:   { 
            type: RELATION_TYPES.TRANSFORMATION, 
            context: 'thunder transformation',
            symbolic: 'Thunder transforms Fire - movement becoming light',
            quantum: 'Movement becoming light'
        },
        ZHEN: { 
            type: RELATION_TYPES.RESONANCE, 
            context: 'thunder resonance',
            symbolic: 'Thunder meets Thunder - movement amplifying movement',
            quantum: 'Resonant movement patterns'
        },
        XUN:  { 
            type: RELATION_TYPES.RESONANCE, 
            context: 'wind resonance',
            symbolic: 'Thunder and Wind - movement meeting flow',
            quantum: 'Movement meeting flow'
        },
        KAN:  { 
            type: RELATION_TYPES.GENERATION, 
            context: 'water generation',
            symbolic: 'Thunder generates Water - movement creating flow',
            quantum: 'Movement creating formlessness'
        },
        GEN:  { 
            type: RELATION_TYPES.OPPOSITION, 
            context: 'mountain opposition',
            symbolic: 'Thunder opposes Mountain - movement meeting stillness',
            quantum: 'Movement meeting structure'
        },
        KUN:  { 
            type: RELATION_TYPES.CONQUEST, 
            context: 'earth conquest',
            symbolic: 'Thunder conquers Earth - movement transforming form',
            quantum: 'Movement dissolving matter'
        }
    },

    // Wind (XUN) - Penetration, Gentleness
    XUN: {
        QIAN: { 
            type: RELATION_TYPES.TRANSFORMATION, 
            context: 'wind transformation',
            symbolic: 'Wind transforms Heaven - flow becoming potential',
            quantum: 'Flow becoming potential'
        },
        DUI:  { 
            type: RELATION_TYPES.SUPPORT, 
            context: 'wind support',
            symbolic: 'Wind supports Lake - flow enabling joy',
            quantum: 'Flow enabling form'
        },
        LI:   { 
            type: RELATION_TYPES.SUPPORT, 
            context: 'wind support',
            symbolic: 'Wind supports Fire - flow enabling light',
            quantum: 'Flow enabling light'
        },
        ZHEN: { 
            type: RELATION_TYPES.RESONANCE, 
            context: 'wind resonance',
            symbolic: 'Wind and Thunder - flow meeting movement',
            quantum: 'Flow meeting movement'
        },
        XUN:  { 
            type: RELATION_TYPES.RESONANCE, 
            context: 'wind resonance',
            symbolic: 'Wind meets Wind - flow amplifying flow',
            quantum: 'Resonant flow patterns'
        },
        KAN:  { 
            type: RELATION_TYPES.GENERATION, 
            context: 'water generation',
            symbolic: 'Wind generates Water - flow creating formlessness',
            quantum: 'Flow creating formlessness'
        },
        GEN:  { 
            type: RELATION_TYPES.OPPOSITION, 
            context: 'mountain opposition',
            symbolic: 'Wind opposes Mountain - flow meeting stillness',
            quantum: 'Flow meeting structure'
        },
        KUN:  { 
            type: RELATION_TYPES.CONQUEST, 
            context: 'earth conquest',
            symbolic: 'Wind conquers Earth - flow transforming form',
            quantum: 'Flow dissolving matter'
        }
    },

    // Water (KAN) - Danger, Mystery
    KAN: {
        QIAN: { 
            type: RELATION_TYPES.CONQUEST, 
            context: 'water conquest',
            symbolic: 'Water conquers Heaven - formlessness dissolving potential',
            quantum: 'Formlessness dissolving potential'
        },
        DUI:  { 
            type: RELATION_TYPES.OPPOSITION, 
            context: 'water opposition',
            symbolic: 'Water opposes Lake - formlessness meeting form',
            quantum: 'Formlessness meeting form'
        },
        LI:   { 
            type: RELATION_TYPES.OPPOSITION, 
            context: 'water opposition',
            symbolic: 'Water opposes Fire - formlessness meeting light',
            quantum: 'Formlessness meeting light'
        },
        ZHEN: { 
            type: RELATION_TYPES.GENERATION, 
            context: 'water generation',
            symbolic: 'Water generates Thunder - formlessness creating movement',
            quantum: 'Formlessness creating movement'
        },
        XUN:  { 
            type: RELATION_TYPES.GENERATION, 
            context: 'water generation',
            symbolic: 'Water generates Wind - formlessness creating flow',
            quantum: 'Formlessness creating flow'
        },
        KAN:  { 
            type: RELATION_TYPES.RESONANCE, 
            context: 'water resonance',
            symbolic: 'Water meets Water - formlessness amplifying formlessness',
            quantum: 'Resonant formlessness patterns'
        },
        GEN:  { 
            type: RELATION_TYPES.RESONANCE, 
            context: 'mountain resonance',
            symbolic: 'Water and Mountain - formlessness meeting stillness',
            quantum: 'Formlessness meeting structure'
        },
        KUN:  { 
            type: RELATION_TYPES.SUPPORT, 
            context: 'earth support',
            symbolic: 'Water supports Earth - formlessness enabling form',
            quantum: 'Formlessness enabling matter'
        }
    },

    // Mountain (GEN) - Stillness, Stability
    GEN: {
        QIAN: { 
            type: RELATION_TYPES.RESONANCE, 
            context: 'mountain resonance',
            symbolic: 'Mountain and Heaven - stillness meeting potential',
            quantum: 'Structure meeting potential'
        },
        DUI:  { 
            type: RELATION_TYPES.RESONANCE, 
            context: 'mountain resonance',
            symbolic: 'Mountain and Lake - stillness meeting joy',
            quantum: 'Structure meeting form'
        },
        LI:   { 
            type: RELATION_TYPES.RESONANCE, 
            context: 'mountain resonance',
            symbolic: 'Mountain and Fire - stillness meeting light',
            quantum: 'Structure meeting light'
        },
        ZHEN: { 
            type: RELATION_TYPES.OPPOSITION, 
            context: 'mountain opposition',
            symbolic: 'Mountain opposes Thunder - stillness meeting movement',
            quantum: 'Structure meeting movement'
        },
        XUN:  { 
            type: RELATION_TYPES.OPPOSITION, 
            context: 'mountain opposition',
            symbolic: 'Mountain opposes Wind - stillness meeting flow',
            quantum: 'Structure meeting flow'
        },
        KAN:  { 
            type: RELATION_TYPES.RESONANCE, 
            context: 'mountain resonance',
            symbolic: 'Mountain and Water - stillness meeting formlessness',
            quantum: 'Structure meeting formlessness'
        },
        GEN:  { 
            type: RELATION_TYPES.RESONANCE, 
            context: 'mountain resonance',
            symbolic: 'Mountain meets Mountain - stillness amplifying stillness',
            quantum: 'Resonant structure patterns'
        },
        KUN:  { 
            type: RELATION_TYPES.SUPPORT, 
            context: 'earth support',
            symbolic: 'Mountain supports Earth - stillness enabling form',
            quantum: 'Structure enabling matter'
        }
    },

    // Earth (KUN) - Pure Yin, Receptivity
    KUN: {
        QIAN: { 
            type: RELATION_TYPES.OPPOSITION, 
            context: 'pure yang opposition',
            symbolic: 'Earth opposes Heaven - form meeting potential',
            quantum: 'Matter meeting potential'
        },
        DUI:  { 
            type: RELATION_TYPES.GENERATION, 
            context: 'earth generation',
            symbolic: 'Earth generates Lake - form creating joy',
            quantum: 'Matter creating form'
        },
        LI:   { 
            type: RELATION_TYPES.GENERATION, 
            context: 'earth generation',
            symbolic: 'Earth generates Fire - form creating light',
            quantum: 'Matter creating light'
        },
        ZHEN: { 
            type: RELATION_TYPES.CONQUEST, 
            context: 'earth conquest',
            symbolic: 'Earth conquers Thunder - form transforming movement',
            quantum: 'Matter dissolving movement'
        },
        XUN:  { 
            type: RELATION_TYPES.CONQUEST, 
            context: 'earth conquest',
            symbolic: 'Earth conquers Wind - form transforming flow',
            quantum: 'Matter dissolving flow'
        },
        KAN:  { 
            type: RELATION_TYPES.SUPPORT, 
            context: 'earth support',
            symbolic: 'Earth supports Water - form enabling formlessness',
            quantum: 'Matter enabling formlessness'
        },
        GEN:  { 
            type: RELATION_TYPES.SUPPORT, 
            context: 'earth support',
            symbolic: 'Earth supports Mountain - form enabling stillness',
            quantum: 'Matter enabling structure'
        },
        KUN:  { 
            type: RELATION_TYPES.RESONANCE, 
            context: 'pure yin resonance',
            symbolic: 'Earth meets Earth - form amplifying form',
            quantum: 'Resonant matter patterns'
        }
    }
};

/**
 * Get relationship between two trigrams
 * @param {string} trigram1 - First trigram key
 * @param {string} trigram2 - Second trigram key
 * @returns {MatrixEntry} Relationship entry
 */
export function getTrigramRelationship(trigram1, trigram2) {
    return TRIGRAM_MATRIX[trigram1]?.[trigram2] || null;
}

/**
 * Get all relationships for a trigram
 * @param {string} trigram - Trigram key
 * @returns {Array<{trigram: string, relationship: MatrixEntry}>} Array of relationships
 */
export function getTrigramRelationships(trigram) {
    return Object.entries(TRIGRAM_MATRIX[trigram] || {})
        .map(([otherTrigram, relationship]) => ({
            trigram: otherTrigram,
            relationship
        }));
}

/**
 * Get relationships of a specific type
 * @param {string} type - Relationship type
 * @returns {Array<{trigram1: string, trigram2: string, relationship: MatrixEntry}>} Array of relationships
 */
export function getRelationshipsByType(type) {
    const relationships = [];
    for (const [trigram1, row] of Object.entries(TRIGRAM_MATRIX)) {
        for (const [trigram2, relationship] of Object.entries(row)) {
            if (relationship.type === type) {
                relationships.push({
                    trigram1,
                    trigram2,
                    relationship
                });
            }
        }
    }
    return relationships;
}

/**
 * Get asymmetric relationships
 * @returns {Array<{trigram1: string, trigram2: string, relationship: MatrixEntry}>} Array of asymmetric relationships
 */
export function getAsymmetricRelationships() {
    const relationships = [];
    for (const [trigram1, row] of Object.entries(TRIGRAM_MATRIX)) {
        for (const [trigram2, relationship] of Object.entries(row)) {
            if (relationship.asymmetric) {
                relationships.push({
                    trigram1,
                    trigram2,
                    relationship
                });
            }
        }
    }
    return relationships;
} 